apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
  labels:
    app: {{ .Release.Name }}-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - name: http-api
    port: 3000
    targetPort: api-port
