apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  endpoints:
  - port: http-api
    path: /metrics
    interval: 5s
