apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-web
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  endpoints:
    - port: metrics-web
      path: /metrics
      interval: 5s
